:- discontiguous pos/1.
:- discontiguous neg/1.

pos(negative_review(s0)).
pos(negative_review(s1)).
pos(negative_review(s2)).
neg(negative_review(s3)).
neg(negative_review(s4)).
neg(negative_review(s5)).
neg(negative_review(s6)).
pos(negative_review(s7)).
neg(negative_review(s8)).
neg(negative_review(s9)).
neg(negative_review(s10)).
neg(negative_review(s11)).
pos(negative_review(s12)).
neg(negative_review(s13)).
pos(negative_review(s14)).
neg(negative_review(s15)).
pos(negative_review(s16)).
pos(negative_review(s17)).
neg(negative_review(s18)).
neg(negative_review(s19)).
pos(negative_review(s20)).
pos(negative_review(s21)).
neg(negative_review(s22)).
neg(negative_review(s23)).
pos(negative_review(s24)).
neg(negative_review(s25)).
neg(negative_review(s26)).
pos(negative_review(s27)).
neg(negative_review(s28)).
pos(negative_review(s29)).
neg(negative_review(s30)).
neg(negative_review(s31)).
pos(negative_review(s32)).
neg(negative_review(s33)).
pos(negative_review(s34)).
neg(negative_review(s35)).
pos(negative_review(s36)).
pos(negative_review(s37)).
neg(negative_review(s38)).
neg(negative_review(s39)).
neg(negative_review(s40)).
neg(negative_review(s41)).
neg(negative_review(s42)).
pos(negative_review(s43)).
neg(negative_review(s44)).
neg(negative_review(s45)).
pos(negative_review(s46)).
neg(negative_review(s47)).
pos(negative_review(s48)).
neg(negative_review(s49)).
neg(negative_review(s50)).
neg(negative_review(s51)).
neg(negative_review(s52)).
neg(negative_review(s53)).
neg(negative_review(s54)).
pos(negative_review(s55)).
neg(negative_review(s56)).
pos(negative_review(s57)).
neg(negative_review(s58)).
pos(negative_review(s59)).
pos(negative_review(s60)).
pos(negative_review(s61)).
pos(negative_review(s62)).
neg(negative_review(s63)).
pos(negative_review(s64)).
pos(negative_review(s65)).
neg(negative_review(s66)).
pos(negative_review(s67)).
pos(negative_review(s68)).
pos(negative_review(s69)).
pos(negative_review(s70)).
neg(negative_review(s71)).
pos(negative_review(s72)).
neg(negative_review(s73)).
pos(negative_review(s74)).
pos(negative_review(s75)).
pos(negative_review(s76)).
neg(negative_review(s77)).
pos(negative_review(s78)).
pos(negative_review(s79)).
pos(negative_review(s80)).
pos(negative_review(s81)).
neg(negative_review(s82)).
neg(negative_review(s83)).
neg(negative_review(s84)).
pos(negative_review(s85)).
neg(negative_review(s86)).
neg(negative_review(s87)).
neg(negative_review(s88)).
pos(negative_review(s89)).
pos(negative_review(s90)).
pos(negative_review(s91)).
pos(negative_review(s92)).
pos(negative_review(s93)).
neg(negative_review(s94)).
pos(negative_review(s95)).
pos(negative_review(s96)).
neg(negative_review(s97)).
pos(negative_review(s98)).
pos(negative_review(s99)).
