:- discontiguous pos/1.
:- discontiguous neg/1.

pos(positive_review(s0)).
neg(positive_review(s1)).
neg(positive_review(s2)).
neg(positive_review(s3)).
pos(positive_review(s4)).
neg(positive_review(s5)).
pos(positive_review(s6)).
pos(positive_review(s7)).
pos(positive_review(s8)).
pos(positive_review(s9)).
neg(positive_review(s10)).
pos(positive_review(s11)).
neg(positive_review(s12)).
pos(positive_review(s13)).
pos(positive_review(s14)).
neg(positive_review(s15)).
pos(positive_review(s16)).
pos(positive_review(s17)).
neg(positive_review(s18)).
pos(positive_review(s19)).
neg(positive_review(s20)).
pos(positive_review(s21)).
neg(positive_review(s22)).
pos(positive_review(s23)).
pos(positive_review(s24)).
pos(positive_review(s25)).
neg(positive_review(s26)).
neg(positive_review(s27)).
neg(positive_review(s28)).
neg(positive_review(s29)).
neg(positive_review(s30)).
neg(positive_review(s31)).
pos(positive_review(s32)).
pos(positive_review(s33)).
neg(positive_review(s34)).
neg(positive_review(s35)).
neg(positive_review(s36)).
pos(positive_review(s37)).
pos(positive_review(s38)).
pos(positive_review(s39)).
pos(positive_review(s40)).
pos(positive_review(s41)).
neg(positive_review(s42)).
neg(positive_review(s43)).
neg(positive_review(s44)).
pos(positive_review(s45)).
neg(positive_review(s46)).
pos(positive_review(s47)).
neg(positive_review(s48)).
neg(positive_review(s49)).
