:- discontiguous pos/1.
:- discontiguous neg/1.

pos(negative_review(s0)).
pos(negative_review(s1)).
neg(negative_review(s2)).
pos(negative_review(s3)).
pos(negative_review(s4)).
neg(negative_review(s5)).
neg(negative_review(s6)).
neg(negative_review(s7)).
neg(negative_review(s8)).
neg(negative_review(s9)).
neg(negative_review(s10)).
neg(negative_review(s11)).
neg(negative_review(s12)).
pos(negative_review(s13)).
neg(negative_review(s14)).
pos(negative_review(s15)).
pos(negative_review(s16)).
neg(negative_review(s17)).
pos(negative_review(s18)).
pos(negative_review(s19)).
neg(negative_review(s20)).
pos(negative_review(s21)).
neg(negative_review(s22)).
neg(negative_review(s23)).
pos(negative_review(s24)).
neg(negative_review(s25)).
pos(negative_review(s26)).
pos(negative_review(s27)).
neg(negative_review(s28)).
neg(negative_review(s29)).
pos(negative_review(s30)).
pos(negative_review(s31)).
pos(negative_review(s32)).
pos(negative_review(s33)).
pos(negative_review(s34)).
pos(negative_review(s35)).
pos(negative_review(s36)).
pos(negative_review(s37)).
neg(negative_review(s38)).
pos(negative_review(s39)).
neg(negative_review(s40)).
neg(negative_review(s41)).
neg(negative_review(s42)).
neg(negative_review(s43)).
neg(negative_review(s44)).
pos(negative_review(s45)).
neg(negative_review(s46)).
pos(negative_review(s47)).
neg(negative_review(s48)).
pos(negative_review(s49)).
neg(negative_review(s50)).
pos(negative_review(s51)).
neg(negative_review(s52)).
pos(negative_review(s53)).
neg(negative_review(s54)).
neg(negative_review(s55)).
pos(negative_review(s56)).
neg(negative_review(s57)).
pos(negative_review(s58)).
neg(negative_review(s59)).
pos(negative_review(s60)).
pos(negative_review(s61)).
pos(negative_review(s62)).
neg(negative_review(s63)).
neg(negative_review(s64)).
pos(negative_review(s65)).
neg(negative_review(s66)).
neg(negative_review(s67)).
pos(negative_review(s68)).
neg(negative_review(s69)).
neg(negative_review(s70)).
pos(negative_review(s71)).
neg(negative_review(s72)).
neg(negative_review(s73)).
pos(negative_review(s74)).
pos(negative_review(s75)).
pos(negative_review(s76)).
