:- discontiguous pos/1.
:- discontiguous neg/1.

pos(negative_review(s0)).
neg(negative_review(s1)).
neg(negative_review(s2)).
pos(negative_review(s3)).
pos(negative_review(s4)).
pos(negative_review(s5)).
pos(negative_review(s6)).
neg(negative_review(s7)).
neg(negative_review(s8)).
neg(negative_review(s9)).
pos(negative_review(s10)).
neg(negative_review(s11)).
pos(negative_review(s12)).
neg(negative_review(s13)).
neg(negative_review(s14)).
pos(negative_review(s15)).
pos(negative_review(s16)).
neg(negative_review(s17)).
pos(negative_review(s18)).
pos(negative_review(s19)).
neg(negative_review(s20)).
neg(negative_review(s21)).
neg(negative_review(s22)).
pos(negative_review(s23)).
pos(negative_review(s24)).
neg(negative_review(s25)).
pos(negative_review(s26)).
neg(negative_review(s27)).
neg(negative_review(s28)).
pos(negative_review(s29)).
pos(negative_review(s30)).
pos(negative_review(s31)).
neg(negative_review(s32)).
pos(negative_review(s33)).
pos(negative_review(s34)).
pos(negative_review(s35)).
neg(negative_review(s36)).
pos(negative_review(s37)).
pos(negative_review(s38)).
neg(negative_review(s39)).
neg(negative_review(s40)).
pos(negative_review(s41)).
pos(negative_review(s42)).
neg(negative_review(s43)).
neg(negative_review(s44)).
neg(negative_review(s45)).
neg(negative_review(s46)).
neg(negative_review(s47)).
neg(negative_review(s48)).
pos(negative_review(s49)).
