:- discontiguous pos/1.
:- discontiguous neg/1.

neg(negative_review(s0)).
pos(negative_review(s1)).
neg(negative_review(s2)).
neg(negative_review(s3)).
pos(negative_review(s4)).
pos(negative_review(s5)).
pos(negative_review(s6)).
pos(negative_review(s7)).
neg(negative_review(s8)).
pos(negative_review(s9)).
neg(negative_review(s10)).
pos(negative_review(s11)).
pos(negative_review(s12)).
neg(negative_review(s13)).
pos(negative_review(s14)).
pos(negative_review(s15)).
neg(negative_review(s16)).
neg(negative_review(s17)).
pos(negative_review(s18)).
neg(negative_review(s19)).
neg(negative_review(s20)).
neg(negative_review(s21)).
pos(negative_review(s22)).
neg(negative_review(s23)).
pos(negative_review(s24)).
neg(negative_review(s25)).
neg(negative_review(s26)).
pos(negative_review(s27)).
neg(negative_review(s28)).
neg(negative_review(s29)).
pos(negative_review(s30)).
neg(negative_review(s31)).
pos(negative_review(s32)).
pos(negative_review(s33)).
pos(negative_review(s34)).
neg(negative_review(s35)).
pos(negative_review(s36)).
pos(negative_review(s37)).
neg(negative_review(s38)).
neg(negative_review(s39)).
